language: php

php:
  - 7.0
  - 7.1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --no-suggest

before_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; chmod +x ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; ./cc-test-reporter before-build; fi

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

notifications:
  email: false
  slack:
    secure: T8rORruaJ5Q4krc2A4sDZeWUugVRrF0e4v9YprPZ2W8SrUVG3mpHtcswPGytldCAi5PZDqmsSkn725T7swwwVzbAeYcU0MNWdMoXTeUK1EXbNNIGSF3w92skurN67mbsPViHFN84o1Uz+ePqZZ2DfKXFQrn6eycbizriuSXw0upA7SLOJaY+dI0Oa7Id5GUrpULFDai69tZQEC2U7HlO75mxLvOdKJCk6ZntEolmh00WwFOO4A8RteoX8YRrffdF+THNj6XCh1OvN4FAdk9xbOOz4BtX3x0Rc/7YXwZnDUGC+3QJyyfDDn9XzUsj72wzyK3sZS+gj/pdckIK0iwYDGJ62LcUSYh5eSss9GRIcqDtizhle67jMMntYHsEC3/8rbb9r36RE+3bUMdNPcd7Anfz7iwL6yDnVTvLRe7n+hR37fdgYIqfsBQJTbuTEOGqISM5BT8+Mu24sVnRhhd0Epg6lVWh3+Gbr4TEz77d790dJRxT2dC9OiSkDSK02ESmPbqWq/9T/ifVX0oil2bF27LkgBr1qoPEySYemNw1nWxlsv85D0E0potq25LBpTWPn7FeiGeYOj6xZsSl86Bmm0BOXnJ1xJf0aSg4RcJElIHtw7IvNjc8ZbOh/8m+KDyxagqa1UWykP95D4omLevsl1cjT0DGNpkD7yl/GrpYoIs=
