language: php
dist: trusty
sudo: false
notifications:
  email: false
branches:
  only:
    - master

env:
  global:
    - CC_TEST_REPORTER_ID=7bc3ed42718fcf5b2250d92a4a2bc166ad2ca3b1dcec63b1e17335ef746b4dea

matrix:
  include:
    - php: 7.1
      env:
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - php: 7.1
      env:
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.0
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.5.*
        - SYMFONY_VERSION=^3.0
        - PHPUNIT_VERSION=^6.5
    - php: 7.2
      env:
        - LARAVEL_VERSION=5.6.*
        - SYMFONY_VERSION=^4.0
        - PHPUNIT_VERSION=^7.0

install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - composer require "symfony/lts:${SYMFONY_VERSION}" --no-update -n
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

before_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then chmod +x ./cc-test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then ./cc-test-reporter before-build; fi

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then vendor/bin/phpunit; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
