language: php
php:
  - 7.0
  - 7.1
env:
  - ILLUMINATE_VERSION=5.4.*
sudo: false
matrix:
  include:
  - php: 7.0
    env: ILLUMINATE_VERSION=5.3.*
  - php: 7.1
    env: ILLUMINATE_VERSION=5.3.*
before_install:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/validation:${ILLUMINATE_VERSION}" --no-update
install:
  - travis_retry composer install --prefer-source --no-interaction --no-suggest
script: vendor/bin/phpunit
notifications:
  email: false
  slack:
    secure: T8rORruaJ5Q4krc2A4sDZeWUugVRrF0e4v9YprPZ2W8SrUVG3mpHtcswPGytldCAi5PZDqmsSkn725T7swwwVzbAeYcU0MNWdMoXTeUK1EXbNNIGSF3w92skurN67mbsPViHFN84o1Uz+ePqZZ2DfKXFQrn6eycbizriuSXw0upA7SLOJaY+dI0Oa7Id5GUrpULFDai69tZQEC2U7HlO75mxLvOdKJCk6ZntEolmh00WwFOO4A8RteoX8YRrffdF+THNj6XCh1OvN4FAdk9xbOOz4BtX3x0Rc/7YXwZnDUGC+3QJyyfDDn9XzUsj72wzyK3sZS+gj/pdckIK0iwYDGJ62LcUSYh5eSss9GRIcqDtizhle67jMMntYHsEC3/8rbb9r36RE+3bUMdNPcd7Anfz7iwL6yDnVTvLRe7n+hR37fdgYIqfsBQJTbuTEOGqISM5BT8+Mu24sVnRhhd0Epg6lVWh3+Gbr4TEz77d790dJRxT2dC9OiSkDSK02ESmPbqWq/9T/ifVX0oil2bF27LkgBr1qoPEySYemNw1nWxlsv85D0E0potq25LBpTWPn7FeiGeYOj6xZsSl86Bmm0BOXnJ1xJf0aSg4RcJElIHtw7IvNjc8ZbOh/8m+KDyxagqa1UWykP95D4omLevsl1cjT0DGNpkD7yl/GrpYoIs=
